name: Build and publish Python distributions to PyPI
on:
  release:
    type: [created]

jobs:
  build-and-publish:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install setuptools wheel
      - name: Build
        run: python setup.py sdist bdist_wheel --universal
      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish
        with:
          user: __token__
          password: ${{ secrets.pypi_password }}
